Repository unb-mds/2024-2-AcheiUnB, pull requests merged in 2024-12, with the labels that each got.

#85 83/config integration front back
  API/AcheiUnB/settings.py
  API/requirements.txt
  web/package-lock.json
  web/package.json
  web/src/services/axios.js
Labels: task, back-end, front-end

#95 Alterações no CSS da página e no arquvio SVG da logo do botão.
  web/src/components/icons/.gitkeep
  web/src/components/icons/Microsoft_logo.svg
  web/src/components/icons/Microsoft_logo2.svg
  web/src/views/Login.vue
Labels: bug, front-end

#93 pequenas alterações no mkdocs.yml
  .github/workflows/docs-v2.yml
  docs/mkdocks.yml
  mkdocs.yml
Labels: documentation

#94 Task(Back-end): Base do sistema de chat no projeto
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/asgi.py
  API/AcheiUnB/settings.py
  API/AcheiUnB/urls.py
  API/chat/__init__.py
  API/chat/admin.py
  API/chat/apps.py
  API/chat/consumers.py
  API/chat/migrations/0001_initial.py
  API/chat/migrations/__init__.py
  API/chat/models.py
  API/chat/routing.py
  API/chat/serializers.py
  API/chat/tests.py
  API/chat/urls.py
  API/chat/views.py
  API/requirements.txt
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
  API/users/templates/users/login.html
Labels: task, back-end

#97 90 91/feat/tela perdidos redirecionamento
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/settings.py
  API/AcheiUnB/static/dist/index-BM3zXh8p.css
  API/AcheiUnB/static/dist/index-CsmleIEa.js
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/urls.py
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
  API/users/templates/index.html
  web/src/views/Login.vue
  web/vite.config.js
Labels: task, back-end, front-end

#101 Melhorias e mudanças à página de documentação
  docs/StoryMap.md
  docs/Visual-identity-v1.md
  docs/front-end/Visual-identity.md
  docs/front-end/figma.md
  docs/front-end/imgs/storymap1.png
  docs/front-end/imgs/storymap2.png
  mkdocs.yml
Labels: documentation

#102 Microsoft(MSAL): Redireciona usuário para a página inicial após login e ajusta fluxo de autenticação
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/asgi.py
  API/AcheiUnB/settings.py
  API/AcheiUnB/static/dist/index-BM3zXh8p.css
  API/AcheiUnB/static/dist/index-CsmleIEa.js
  API/AcheiUnB/urls.py
  API/requirements.txt
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/adapters.py
  API/users/apps.py
  API/users/models.py
  API/users/signals.py
  API/users/templates/users/login.html
  API/users/tests.py
  API/users/urls.py
  API/users/views.py
  web/src/views/Login.vue
Labels: bug, back-end, front-end

#103 Correções na documentação de DevOps
  docs/Architecture.md
  mkdocs.yml
Labels: documentation

#104 Criação da tela de achados
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/static/dist/assets/bone-DE10Yqga.png
  API/AcheiUnB/static/dist/assets/caneta-CQ7HO7XX.png
  API/AcheiUnB/static/dist/assets/carteira-Dk-44drH.png
  API/AcheiUnB/static/dist/assets/gloss-CzT_QGW8.png
  API/AcheiUnB/static/dist/assets/index-B8Uo463z.css
  API/AcheiUnB/static/dist/assets/sombrinha-B7Nq8G48.png
  API/AcheiUnB/static/dist/index-BM3zXh8p.css
  API/AcheiUnB/static/dist/index-CsmleIEa.js
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-DnGNr4YP.js
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
  API/users/templates/index.html
  API/users/views.py
  web/src/assets/icons/Microsoft_logo2.svg
  web/src/assets/icons/add-item.svg
  web/src/assets/icons/arrow-left.svg
  web/src/assets/icons/arrow-right.svg
  web/src/assets/icons/image.svg
  web/src/assets/icons/locale.svg
  web/src/assets/images/bone.png
  web/src/assets/images/caneta.png
  web/src/assets/images/carteira.png
  web/src/assets/images/gloss.png
  web/src/assets/images/not-available.png
  web/src/assets/images/sombrinha.png
  web/src/components/Button-Add.vue
  web/src/components/Header.vue
  web/src/components/Item-Card.vue
  web/src/components/Logo.vue
  web/src/components/Sub-Menu.vue
  web/src/router/index.js
  web/src/views/Found.vue
  web/src/views/Login.vue
  web/src/views/Lost.vue
  web/tailwind.config.js
  web/vite.config.js
Labels: enhancement, front-end

#108 Task(Heroku/chats): Implementação da hospedagem do banco de dados e correção na implementação inicial do chat
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/settings.py
  API/chat/consumers.py
  API/chat/migrations/0002_remove_message_chat_chatroom_message_room_and_more.py
  API/chat/models.py
  API/chat/routing.py
  API/chat/serializers.py
  API/chat/urls.py
  API/chat/views.py
  API/docker-compose.yml
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
Labels: task, devops

#110 Task(Cadastro): Implementação de melhorias no gerenciamento de itens perdidos e achados
  API/AcheiUnB/settings.py
  API/requirements.txt
  API/users/migrations/0002_category_remove_item_image_item_color_and_more.py
  API/users/models.py
  API/users/serializers.py
  API/users/urls.py
  API/users/views.py
  docs/front-end/figma.md
Labels: task, back-end

#113 Task(Barcode): Adicionar suporte ao "barcode" para itens valiosos e integração com categorias, marcas e cores
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/entrypoint.sh
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/migrations/0003_brand_color_alter_item_description_item_brand_and_more.py
  API/users/models.py
  API/users/serializers.py
  API/users/urls.py
  API/users/views.py
Labels: task, back-end

#114 Task(user): Gerenciar dados do usuário Microsoft Graph
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/settings.py
  API/AcheiUnB/urls.py
  API/media/user_photos/42.jpg
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/adapters.py
  API/users/apps.py
  API/users/migrations/0003_userprofile.py
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
  API/users/models.py
  API/users/signals.py
  API/users/urls.py
  API/users/views.py
Labels: task, back-end

#116 Criação e personalização de um favicon para o projeto
  web/index.html
  web/src/assets/icons/Favicon.png
  web/src/assets/icons/Lupa1.png
Labels: task, front-end

#119 Task(Cloudinary): Implementado a funcionalidade de upload de imagens para o Cloudinary.
  API/AcheiUnB/settings.py
  API/requirements.txt
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/serializers.py
  API/users/views.py
Labels: enhancement, back-end

#121 Task(Ruff): Integração do Ruff para Linting e Formatação de Código
  .gitignore
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/asgi.py
  API/AcheiUnB/settings.py
  API/AcheiUnB/urls.py
  API/AcheiUnB/wsgi.py
  API/chat/consumers.py
  API/chat/migrations/0001_initial.py
  API/chat/migrations/0002_remove_message_chat_chatroom_message_room_and_more.py
  API/chat/models.py
  API/chat/routing.py
  API/chat/serializers.py
  API/chat/urls.py
  API/chat/views.py
  API/docker-compose.yml
  API/entrypoint.sh
  API/items/guardaCHuva.jpeg
  API/items/guardaCHuva_54vJY00.jpeg
  API/manage.py
  API/pyproject.toml
  API/requirements.txt
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/adapters.py
  API/users/admin.py
  API/users/apps.py
  API/users/migrations/0001_initial.py
  API/users/migrations/0002_category_remove_item_image_item_color_and_more.py
  API/users/migrations/0003_brand_color_alter_item_description_item_brand_and_more.py
  API/users/migrations/0003_userprofile.py
  API/users/migrations/0004_merge_20241229_1953.py
  API/users/models.py
  API/users/serializers.py
  API/users/signals.py
  API/users/tests.py
  API/users/urls.py
  API/users/views.py
Labels: bug, documentation, enhancement, task, devops
