Repository unb-mds/2024-2-AcheiUnB, pull requests merged in 2024-11, with the labels that each got.

#10 docs(mkdocs): Template para descrição das sprints
  docs/sprints/sprint-template.md
Labels: documentation, task

#12 docs(mkdocs): Ajuste na pasta Coelhos
  Coelhos/Rabbit(Estudo): Introdução ao Django Channels, Celery e Redis.md
  docs/sprints/sprint-2.md
Labels: documentation, task

#19 Task(PostgreSQL): Configuração, execução das migrações e ajustes de permissões
  API/AcheiUnB/__pycache__/settings.cpython-312.pyc
  API/AcheiUnB/settings.py
  API/venv/lib/python3.12/site-packages/psycopg2-2.9.10.dist-info/INSTALLER
  API/venv/lib/python3.12/site-packages/psycopg2-2.9.10.dist-info/LICENSE
  API/venv/lib/python3.12/site-packages/psycopg2-2.9.10.dist-info/METADATA
  API/venv/lib/python3.12/site-packages/psycopg2-2.9.10.dist-info/RECORD
  API/venv/lib/python3.12/site-packages/psycopg2-2.9.10.dist-info/REQUESTED
  API/venv/lib/python3.12/site-packages/psycopg2-2.9.10.dist-info/WHEEL
  API/venv/lib/python3.12/site-packages/psycopg2-2.9.10.dist-info/top_level.txt
  API/venv/lib/python3.12/site-packages/psycopg2/__init__.py
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/__init__.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/_ipaddress.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/_json.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/_range.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/errorcodes.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/errors.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/extensions.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/extras.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/pool.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/sql.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/__pycache__/tz.cpython-312.pyc
  API/venv/lib/python3.12/site-packages/psycopg2/_ipaddress.py
  API/venv/lib/python3.12/site-packages/psycopg2/_json.py
  API/venv/lib/python3.12/site-packages/psycopg2/_psycopg.cpython-312-x86_64-linux-gnu.so
  API/venv/lib/python3.12/site-packages/psycopg2/_range.py
  API/venv/lib/python3.12/site-packages/psycopg2/errorcodes.py
  API/venv/lib/python3.12/site-packages/psycopg2/errors.py
  API/venv/lib/python3.12/site-packages/psycopg2/extensions.py
  API/venv/lib/python3.12/site-packages/psycopg2/extras.py
  API/venv/lib/python3.12/site-packages/psycopg2/pool.py
  API/venv/lib/python3.12/site-packages/psycopg2/sql.py
  API/venv/lib/python3.12/site-packages/psycopg2/tz.py
  API/venv/lib/python3.12/site-packages/psycopg2_binary-2.9.10.dist-info/INSTALLER
  API/venv/lib/python3.12/site-packages/psycopg2_binary-2.9.10.dist-info/LICENSE
  API/venv/lib/python3.12/site-packages/psycopg2_binary-2.9.10.dist-info/METADATA
  API/venv/lib/python3.12/site-packages/psycopg2_binary-2.9.10.dist-info/RECORD
  API/venv/lib/python3.12/site-packages/psycopg2_binary-2.9.10.dist-info/REQUESTED
  API/venv/lib/python3.12/site-packages/psycopg2_binary-2.9.10.dist-info/WHEEL
  API/venv/lib/python3.12/site-packages/psycopg2_binary-2.9.10.dist-info/top_level.txt
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libcom_err-2abe824b.so.2.1
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libcrypto-ea28cefb.so.1.1
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libgssapi_krb5-497db0c6.so.2.2
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libk5crypto-b1f99d5c.so.3.1
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libkeyutils-dfe70bd6.so.1.5
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libkrb5-fcafa220.so.3.3
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libkrb5support-d0bcff84.so.0.1
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/liblber-e0f57070.so.2.0.200
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libldap-c37ed727.so.2.0.200
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libpcre-9513aab5.so.1.2.0
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libpq-e8a033dd.so.5.16
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libsasl2-883649fd.so.3.0.0
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libselinux-0922c95c.so.1
  API/venv/lib/python3.12/site-packages/psycopg2_binary.libs/libssl-3e69114b.so.1.1
Labels: task, back-end

#20 Docs(Mkdocs): Ajuste na pasta Coelhos
  Coelhos/Rabbit(Estudo): Testes unitários e CodeCov.md
Labels: documentation, rabbit

#22 Docs(Mkdocs): Realização do Protótipo de Arquitetura
  Coelhos/Rabbit(Estudo): Introdução ao Django Channels, Celery e Redis.md
  README.md
  docs/Architecture.md
  docs/Task(Docs): Documentação para Padrões de Commit e Nomeação de Branches.md
  docs/sprints/sprint-2.md
  docs/sprints/sprint-3.md
Labels: documentation

#29 Create Rabbit(Estudo): Trazer soluções para a configuração dos ambientes
  Coelhos/Rabbit(Estudo): Trazer soluções para a configuração dos ambientes
Labels: rabbit, to study, devops

#30 Docs(Mkdocs): Criação do arquivo da Sprint 3
  docs/front-end/Visual-identity.md
  docs/sprints/sprint-3.md
  docs/sprints/sprint-4.md
Labels: documentation, sprint

#33 Task(DevOps): Implementação do Docker ao projeto
  docker/Django/__init__.py
  docker/Django/__pycache__/__init__.cpython-312.pyc
  docker/Django/__pycache__/settings.cpython-312.pyc
  docker/Django/__pycache__/urls.cpython-312.pyc
  docker/Django/__pycache__/wsgi.cpython-312.pyc
  docker/Django/asgi.py
  docker/Django/settings.py
  docker/Django/urls.py
  docker/Django/wsgi.py
  docker/Dockerfile
  docker/api/settings.py
  docker/db.sqlite3
  docker/docker-compose.yml
  docker/manage.py
  docker/requirements.txt
Labels: task, devops

#34 Taks(Backend): Atualizando Requisitos para o Backend
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/settings.cpython-310.pyc
  API/AcheiUnB/__pycache__/settings.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/db.sqlite3
  API/requirements.txt
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
Labels: task, back-end

#32 Task(DevOps): Criação e implementação inicial do workflow de pipeline CI
  .github/workflows/pipeline-ci.yaml
Labels: task, devops

#43 Task(DevOps): Revisar Docker e Kubernetes e avaliar a possibilidade de implementação do Kubernetes no projeto
  Coelhos/Rabbit(Estudo): Docker e Kubernetes.md
Labels: task, devops

#45 Task(Backend): Correção de Bugs
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/settings.py
  API/docker-compose.yml
  API/entrypoint.sh
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
Labels: bug, task, back-end

#46 Feat/add figma docs v1
  docs/front-end/figma.md
  docs/front-end/imgs/01.png
  docs/front-end/imgs/02.png
  docs/front-end/imgs/03.png
  docs/front-end/imgs/04.png
  docs/front-end/imgs/05.png
  docs/front-end/imgs/06.png
  docs/front-end/imgs/07.png
  docs/front-end/imgs/tela_prototipo1.png
  docs/front-end/imgs/tela_prototipo2.png
  docs/front-end/imgs/tela_prototipo3.png
Labels: documentation, front-end

#50 Criação e organização inicial do site de documentação
  docs/documentacao-padroes-commits-branches.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#53 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#59 feat(api): implementação do backend para itens achados e perdidos e melhorias no login
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/settings.py
  API/AcheiUnB/urls.py
  API/items/guardaCHuva.jpeg
  API/items/guardaCHuva_54vJY00.jpeg
  API/requirements.txt
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/migrations/0001_initial.py
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
  API/users/models.py
  API/users/serializers.py
  API/users/templates/users/login.html
  API/users/urls.py
  API/users/views.py
Labels: task, back-end

#63 Create prototype.md
  docs/front-end/prototype.md
Labels: front-end

#62 Task(MKdocs): Ajuste no README
  README.md
Labels: documentation, task

#60 Docs(CODE_OF_CONDUCT): Definindo o código de conduta do projeto
  docs/CODE_OF_CONDUCT.md
Labels: documentation, task

#66 Task(MKdocs): Adição do direcionamento ao protótipo do AcheiUnB no README
  README.md
Labels: documentation, task

#70 Task(DevOps): Estudo sobre o serviço de hospedagem
  Coelhos/Rabbit(Estudo): Serviço de Hospedagem.md
Labels: to study, task, devops

#72 Task(Mkdocs): Adicionar documento Contributing
  docs/CONTRIBUTING.md
Labels: documentation

#78 Task(MKdocs): Alteração da forma de listar os objetivos das Sprints
  docs/sprints/sprint-0.md
  docs/sprints/sprint-1.md
  docs/sprints/sprint-2.md
  docs/sprints/sprint-3.md
  docs/sprints/sprint-4.md
  docs/sprints/sprint-5.md
  docs/sprints/sprint-6.md
  docs/sprints/sprint-template.md
Labels: documentation, task

#81 75/docs/criar o documento de security policy
  docs/SECURITY.md
Labels: documentation

#82 Avaliar alternativas (caso não caiba a utilização do Heroku no projeto).
  Coelhos/Rabbit(Estudo): Comparativo de possíveis tecnologias de hospedagem para o projeto.md
Labels: to study, task, devops

#84 Task(Back-end): Alteração da URL de login para a raiz da aplicação
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/settings.py
  API/AcheiUnB/urls.py
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
Labels: task, back-end
