Repository unb-mds/2024-2-AcheiUnB, pull requests merged in 2025-02, with the labels that each got.

#190 Feat(user): Criação da página de usuário
  web/src/views/User.vue
Labels: enhancement, task

#194 Task(front): Criação do botão "Como Contribuir?", ajustes na tela de usuário e melhoria no email de boas-vindas
  API/users/templates/emails/welcome.html
  web/src/views/About.vue
  web/src/views/User.vue
Labels: task, front-end

#196 feat(fornt): design dos botões de paginação
  web/src/views/Found.vue
  web/src/views/Lost.vue
Labels: front-end

#198 195/front/design dos botões de paginação
  web/src/views/Lost.vue
Labels: front-end

#204 Fix(item): Corrigindo bugs da listagem do item
  web/src/views/ListItem.vue
Labels: bug, back-end, front-end, javascript, python

#207 Task(Front): Adicionar uma mensagem e desenho quando não houver itens nas páginas
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/found-and-lost-box-BB3OpleO.jpg
  API/AcheiUnB/static/dist/assets/index-C9VhPuY6.css
  API/AcheiUnB/static/dist/assets/index-aaMZN4nb.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-B3_bU_73.js
  API/AcheiUnB/static/dist/js/index-BnoWY_TY.js
  API/celerybeat-schedule
  web/src/assets/icons/found-and-lost-box.jpg
  web/src/components/Empty-State-User.vue
  web/src/components/Empty-State.vue
  web/src/views/Found.vue
  web/src/views/Lost.vue
  web/src/views/UserItems-Found.vue
  web/src/views/UserItems-Lost.vue
Labels: task, front-end

#208 Task(Front): Customizar a confirmação de deleção de itens em "meus itens"
  API/AcheiUnB/static/dist/assets/index-Dslx85AU.css
  API/AcheiUnB/static/dist/js/index-BB4p2H0C.js
  API/celerybeat-schedule
  web/src/components/Item-Card.vue
  web/src/views/UserItems-Found.vue
  web/src/views/UserItems-Lost.vue
  web/vite.config.js.timestamp-1739078070804-fa9f558db6b37.mjs
Labels: task, front-end

#209 feat(front): Criação da tela de chat
  web/src/assets/icons/user.svg
  web/src/components/Chatroom.vue
  web/src/views/Chats.vue
  web/src/views/Message.vue
  web/src/views/User.vue
Labels: front-end

#216 214/task/chat resolver problemas
  API/chat/serializers.py
  API/chat/views.py
  web/src/components/Header-Message.vue
  web/src/views/Chats.vue
Labels: bug, task, front-end, javascript

#220 Task(front): Editar itens e corrigir token vencido na rota meus itens.
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-r67W0Xa0.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-DrhWDhWw.js
  API/celerybeat-schedule
  web/src/assets/icons/EditarPerfil.svg
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
  web/src/components/Item-Header.vue
  web/src/router/index.js
  web/src/views/EditItem.vue
  web/src/views/ListItem.vue
Labels: bug, task, front-end

#222 Task(labels-filtros): Ajuste das labels dos filtros
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/default-avatar-BpcudYYH.png
  API/AcheiUnB/static/dist/assets/index-C9VhPuY6.css
  API/AcheiUnB/static/dist/assets/index-Dslx85AU.css
  API/AcheiUnB/static/dist/assets/index-k303jj23.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-BB4p2H0C.js
  API/AcheiUnB/static/dist/js/index-BnoWY_TY.js
  API/AcheiUnB/static/dist/js/index-D96LntmE.js
  API/celerybeat-schedule
  web/src/components/SearchBar.vue
  web/src/views/Found.vue
  web/src/views/Lost.vue
Labels: task, front-end

#226 199/front/adiciona ajustes gerais
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-CZ44oVY3.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-DagMRiY7.js
  API/celerybeat-schedule
  web/src/assets/icons/add-item.svg
  web/src/assets/icons/locale.svg
  web/src/components/Button-Add-Found.vue
  web/src/components/Button-Add-Lost.vue
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
  web/src/components/Header-About.vue
  web/src/components/Header-Found.vue
  web/src/components/Header-Lost.vue
  web/src/components/Header-Message.vue
  web/src/components/Item-Card.vue
  web/src/components/Item-Header.vue
  web/src/components/Main-Menu.vue
  web/src/components/Search-Header.vue
  web/src/components/SearchBar.vue
  web/src/components/Sub-Menu-Found.vue
  web/src/components/Sub-Menu-Lost.vue
  web/src/components/Sub-Menu-UserFound.vue
  web/src/components/Sub-Menu-UserLost.vue
  web/src/router/index.js
  web/src/services/api.js
  web/src/services/apiItems.js
  web/src/views/About.vue
  web/src/views/Anonimo.vue
  web/src/views/Chats.vue
  web/src/views/Found.vue
  web/src/views/Login.vue
  web/src/views/Lost.vue
  web/src/views/Session-Expired.vue
  web/src/views/User.vue
  web/src/views/UserItems-Lost.vue
Labels: front-end

#231 223/task/erros personalizados ajuste em botões
  API/AcheiUnB/__init__.py
  API/AcheiUnB/celery.py
  API/AcheiUnB/settings.py
  API/AcheiUnB/urls.py
  API/AcheiUnB/wsgi.py
  API/Dockerfile
  API/chat/consumers.py
  API/manage.py
  API/media/user_photos/42.jpg
  API/users/apps.py
  API/users/authentication.py
  API/users/match.py
  API/users/models.py
  API/users/pagination.py
  API/users/serializers.py
  API/users/signals.py
  API/users/tasks.py
  API/users/urls.py
  API/users/views.py
  mkdocs.yml
  web/src/assets/images/bone.png
  web/src/assets/images/caneta.png
  web/src/assets/images/carteira.png
  web/src/assets/images/gloss.png
  web/src/assets/images/sombrinha.png
  web/src/assets/main.css
  web/src/components/Empty-State-User.vue
  web/src/components/Empty-State.vue
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
  web/src/components/Item-Card.vue
  web/src/components/Item-Header.vue
  web/src/components/Main-Menu.vue
  web/src/components/SearchBar.vue
  web/src/services/apiItems.js
  web/src/views/Chats.vue
  web/src/views/EditItem.vue
  web/src/views/Found.vue
  web/src/views/ListItem.vue
  web/src/views/Lost.vue
  web/src/views/Message.vue
  web/src/views/User.vue
  web/src/views/UserItems-Found.vue
  web/src/views/UserItems-Lost.vue
  web/vite.config.js.timestamp-1737591904521-0fc9098e872e2.mjs
  web/vite.config.js.timestamp-1737594586659-8dd51d71f8313.mjs
  web/vite.config.js.timestamp-1738035132545-417108b6bc18f.mjs
  web/vite.config.js.timestamp-1739078070804-fa9f558db6b37.mjs
Labels: bug, task, front-end

#229 Task(migration): povoar o banco de dados com categorias marcas cores e locais
  API/users/migrations/0011_populate_initial_data.py
  API/users/tests/test_APITestItemFilters.py
  API/users/tests/test_TestCloudinaryImageDeletion.py
  API/users/tests/test_task.py
  API/users/tests/test_views.py
  API/users/views.py
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
Labels: bug, enhancement, task, back-end, front-end, javascript, python

#233 fix(geral): corrige erros gerais de arquivos e componentes
  API/users/urls.py
  web/src/assets/main.css
  web/src/components/Empty-State-User.vue
  web/src/views/ListItem.vue
Labels: bug, task, back-end, front-end

#236 Task(docs): Documentado todas as APIs
  API/AcheiUnB/settings.py
  API/AcheiUnB/urls.py
  API/chat/views.py
  API/requirements.txt
  API/users/views.py
Labels: documentation, back-end
