Repository unb-mds/2024-2-AcheiUnB, pull requests merged in 2025-05, with the labels that each got.

#255 Fix(Cadastro de Item): Controle para evitar criação múltipla de itens ao clicar no botão de cadastro
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-k303jj23.css
  API/AcheiUnB/static/dist/assets/index-r67W0Xa0.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-D96LntmE.js
  API/AcheiUnB/static/dist/js/index-DdAcjziC.js
  API/AcheiUnB/static/dist/js/index-DrhWDhWw.js
  API/users/views.py
  web/.env.production
  web/package-lock.json
  web/src/components/Alert.vue
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
Labels: bug, front-end, javascript

#258 Fix(chat): corrigir paginação das mensagens no chat limite de 40, limpar mensagem antiga e ajuste no na ordenação das mensagens
  API/chat/views.py
  API/users/pagination.py
  API/users/tasks.py
  web/src/views/Found.vue
  web/src/views/Login.vue
  web/src/views/Lost.vue
Labels: bug, enhancement, back-end, python

#259 Fix(tela de login): Centralizado os elementos, imagem padrão corrigida e responsividade aprimorada
  web/src/views/Login.vue
  web/tailwind.config.js
Labels: bug, front-end, javascript

#260 Fix(VM): Ajustes de configuração feitos direto na VM para produção
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/index.html
  API/celerybeat-schedule
  API/docker-compose.prod.yml
  API/nginx.conf
  API/users/views.py
  web/.env.production
Labels: bug, enhancement, task, back-end, devops, dependencies, python

#262 Refactor(Painel): Configuração do Painel Admin + Middleware de Banimento + Notificação Assíncrona
  API/AcheiUnB/settings.py
  API/AcheiUnB/settings_production.py
  API/users/admin.py
  API/users/middleware.py
  API/users/migrations/0012_userprofile_is_banned.py
  API/users/models.py
  API/users/signals.py
  API/users/tasks.py
Labels: enhancement, task, back-end, devops, python

#267 Task(develop): atualizando a main com todas as mudanças
  API/AcheiUnB/settings.py
  API/AcheiUnB/settings_production.py
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-k303jj23.css
  API/AcheiUnB/static/dist/assets/index-r67W0Xa0.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-D96LntmE.js
  API/AcheiUnB/static/dist/js/index-DdAcjziC.js
  API/AcheiUnB/static/dist/js/index-DrhWDhWw.js
  API/celerybeat-schedule
  API/chat/views.py
  API/docker-compose.prod.yml
  API/nginx.conf
  API/users/admin.py
  API/users/middleware.py
  API/users/migrations/0012_userprofile_is_banned.py
  API/users/models.py
  API/users/pagination.py
  API/users/signals.py
  API/users/tasks.py
  API/users/views.py
  web/.env.production
  web/package-lock.json
  web/src/components/Alert.vue
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
  web/src/views/Found.vue
  web/src/views/Login.vue
  web/src/views/Lost.vue
  web/src/views/Session-Expired.vue
  web/tailwind.config.js
Labels: bug, documentation, enhancement, task, back-end, front-end, devops, sprint, dependencies, javascript, python
