Repository unb-mds/2024-2-AcheiUnB, pull requests merged in 2025-01, with the labels that each got.

#122 Task(Sprints-da-Loucura): Merge das Sprints realizadas no recesso consolidando melhorias e novas funcionalidades ao projeto
  .gitignore
  API/AcheiUnB/__pycache__/__init__.cpython-312.pyc
  API/AcheiUnB/__pycache__/urls.cpython-312.pyc
  API/AcheiUnB/__pycache__/wsgi.cpython-312.pyc
  API/AcheiUnB/asgi.py
  API/AcheiUnB/settings.py
  API/AcheiUnB/static/dist/assets/Favicon-DZaE_dAz.png
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/urls.py
  API/AcheiUnB/wsgi.py
  API/chat/consumers.py
  API/chat/migrations/0001_initial.py
  API/chat/migrations/0002_remove_message_chat_chatroom_message_room_and_more.py
  API/chat/models.py
  API/chat/routing.py
  API/chat/serializers.py
  API/chat/urls.py
  API/chat/views.py
  API/docker-compose.yml
  API/entrypoint.sh
  API/items/guardaCHuva.jpeg
  API/items/guardaCHuva_54vJY00.jpeg
  API/manage.py
  API/media/user_photos/42.jpg
  API/pyproject.toml
  API/requirements.txt
  API/users/__pycache__/__init__.cpython-312.pyc
  API/users/__pycache__/admin.cpython-312.pyc
  API/users/__pycache__/apps.cpython-312.pyc
  API/users/__pycache__/models.cpython-312.pyc
  API/users/__pycache__/views.cpython-312.pyc
  API/users/adapters.py
  API/users/admin.py
  API/users/apps.py
  API/users/migrations/0001_initial.py
  API/users/migrations/0002_category_remove_item_image_item_color_and_more.py
  API/users/migrations/0003_brand_color_alter_item_description_item_brand_and_more.py
  API/users/migrations/0003_userprofile.py
  API/users/migrations/0004_merge_20241229_1953.py
  API/users/migrations/__pycache__/__init__.cpython-312.pyc
  API/users/models.py
  API/users/serializers.py
  API/users/signals.py
  API/users/templates/index.html
  API/users/tests.py
  API/users/urls.py
  API/users/views.py
  web/index.html
  web/src/assets/icons/Favicon.png
  web/src/assets/icons/Lupa1.png
Labels: documentation, task, back-end, front-end, devops, dependencies

#128 Update pipeline-ci.yaml
  .github/workflows/pipeline-ci.yaml
Labels: task, devops

#134 Feat/Refactor(Rodar-Projeto/Item): Automatização de Execução, Inclusão do campo Location com id único adicionado ao barcode e Atualização do README
  .gitignore
  API/chat/serializers.py
  API/chat/views.py
  API/users/migrations/0005_location_alter_item_location.py
  API/users/models.py
  API/users/serializers.py
  API/users/urls.py
  API/users/views.py
  Makefile
  README.md
Labels: back-end, devops

#137 Refactor(build):Integrando Front com Back para produção com as novas atualizações
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-DUO5BpO3.css
  API/AcheiUnB/static/dist/assets/index-DZIDT3qk.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-Dk_5UPN2.js
  API/AcheiUnB/static/dist/js/index-Dmqp8QMV.js
Labels: devops

#143 142/feat/organiza-estrutura-front
  web/src/components/Form.vue
  web/src/models/Form.js
  web/src/models/Item.js
  web/src/services/api.js
  web/src/services/axios.js
Labels: front-end

#144 Refactor(Item): Remoção do campo é valioso
  API/users/migrations/0006_remove_item_is_valuable.py
  API/users/models.py
  API/users/serializers.py
  API/users/views.py
Labels: task, back-end

#147 Feat(Match): Implementação de Match de Itens com Notificação Automática por Email com Possíveis Matches
  API/AcheiUnB/settings.py
  API/users/match.py
  API/users/migrations/0007_item_barcode.py
  API/users/models.py
  API/users/serializers.py
  API/users/templates/emails/match_notification.html
  API/users/tests.py
  API/users/urls.py
  API/users/utils.py
  API/users/views.py
Labels: task, back-end

#149 Fix(Campos): Corrige erro ao iniciar o projeto com os campos Location e Category como obrigatórios
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-DUO5BpO3.css
  API/AcheiUnB/static/dist/assets/index-DfGykJth.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-CZWYHv9B.js
  API/AcheiUnB/static/dist/js/index-Dk_5UPN2.js
  API/users/match.py
  API/users/migrations/0008_alter_item_category_alter_item_location.py
  API/users/models.py
  API/users/serializers.py
  API/users/views.py
Labels: bug, back-end

#148 feat(cleanup): adicionar comando para excluir itens antigos e chats vinculados
  API/users/asds/__init__.py
  API/users/management/commands/__init__.py
  API/users/management/commands/clean_old_items.py
  API/users/models.py
  API/users/tests.py
Labels: back-end, devops

#150 Task(front): Criação do menu de filtros e adição dos itens existens na página inicial
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/bone-DE10Yqga.png
  API/AcheiUnB/static/dist/assets/caneta-CQ7HO7XX.png
  API/AcheiUnB/static/dist/assets/carteira-Dk-44drH.png
  API/AcheiUnB/static/dist/assets/gloss-CzT_QGW8.png
  API/AcheiUnB/static/dist/assets/index-B9FDQVu9.css
  API/AcheiUnB/static/dist/assets/sombrinha-B7Nq8G48.png
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-Cnhd7DxK.js
  web/src/components/Item-Card.vue
  web/src/components/SearchBar.vue
  web/src/services/apiItems.js
  web/src/utils/dateUtils.js
  web/src/views/Found.vue
  web/src/views/Lost.vue
Labels: task, front-end

#153 Refactor(Filtro): Melhorias em Filtros, Busca, Ordenação e Testes de Itens
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-B9FDQVu9.css
  API/AcheiUnB/static/dist/assets/index-DfGykJth.css
  API/AcheiUnB/static/dist/assets/index-dr31crJK.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-CZWYHv9B.js
  API/AcheiUnB/static/dist/js/index-Cnhd7DxK.js
  API/AcheiUnB/static/dist/js/index-vlZZF_fn.js
  API/users/authentication.py
  API/users/filters.py
  API/users/serializers.py
  API/users/tests.py
  API/users/views.py
Labels: back-end

#157 Refactor(Item): Verificado a edição de itens e Implementado a manipulação e exclusão segura de imagens por parte dos usuários
  API/AcheiUnB/settings.py
  API/users/apps.py
  API/users/serializers.py
  API/users/signals.py
  API/users/tests.py
  API/users/views.py
Labels: enhancement, task, back-end

#160 Task(front): Criação da página de sobre do projeto e da página de cadastro de itens perdidos
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-ByZYjVXp.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-DfmOQaTF.js
  web/src/components/Button-Add-Found.vue
  web/src/components/Button-Add-Lost.vue
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
  web/src/components/Header-About.vue
  web/src/components/Header-Found.vue
  web/src/components/Header-Lost.vue
  web/src/components/Header.vue
  web/src/components/Main-Menu.vue
  web/src/router/index.js
  web/src/views/About.vue
  web/src/views/Register-Found.vue
  web/src/views/Register-Lost.vue
  web/tailwind.config.js
  web/vite.config.js.timestamp-1737591904521-0fc9098e872e2.mjs
  web/vite.config.js.timestamp-1737594586659-8dd51d71f8313.mjs
Labels: task, front-end

#166 Task(Celery) Adição do Celery ao projeto
  API/AcheiUnB/__init__.py
  API/AcheiUnB/celery.py
  API/AcheiUnB/settings.py
  API/Dockerfile
  API/celerybeat-schedule
  API/docker-compose.yml
  API/entrypoint.sh
  API/requirements.txt
  API/users/tasks.py
Labels: enhancement, task, back-end, devops

#168 Task(Celery): Otimização da criação e edição de itens com Celery, match e gerenciamento de imagens
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-BQEbqW89.css
  API/AcheiUnB/static/dist/assets/index-ByZYjVXp.css
  API/AcheiUnB/static/dist/assets/index-dr31crJK.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-DfmOQaTF.js
  API/AcheiUnB/static/dist/js/index-qKxAHp-g.js
  API/AcheiUnB/static/dist/js/index-vlZZF_fn.js
  API/users/apps.py
  API/users/match.py
  API/users/serializers.py
  API/users/tasks.py
  API/users/templates/emails/welcome.html
  API/users/urls.py
  API/users/utils.py
  API/users/views.py
  web/src/components/Form-Lost.vue
Labels: enhancement, task, back-end, devops, dependencies, python

#171 Task(Celery): Agendar task da deleção do itens e chats relacionados após 2 semanas
  API/AcheiUnB/settings.py
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-Cu98-bPz.js
  API/AcheiUnB/static/dist/js/index-qKxAHp-g.js
  API/celerybeat-schedule
  API/docker-compose.yml
  API/requirements.txt
  API/users/management/commands/__init__.py
  API/users/management/commands/clean_old_items.py
  API/users/match.py
  API/users/pagination.py
  API/users/tasks.py
  API/users/templates/emails/match_notification.html
  API/users/urls.py
  API/users/views.py
  web/src/services/apiItems.js
  web/src/views/Found.vue
  web/src/views/Lost.vue
Labels: enhancement, task, back-end, dependencies

#169 feat(autenticação): Criação de um endpoint que valida a autenticação …
  API/users/urls.py
  API/users/views.py
  web/src/router/index.js
  web/src/services/api.js
Labels: back-end, front-end

#178 Task(página): Implementado a Página "Meus Itens"
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/assets/index-CfSxScXu.css
  API/AcheiUnB/static/dist/assets/index-ZFZIwXtu.css
  API/AcheiUnB/static/dist/index.html
  API/AcheiUnB/static/dist/js/index-DXsdOItS.js
  API/AcheiUnB/static/dist/js/index-rL_VW9Ks.js
  API/users/urls.py
  API/users/views.py
  web/src/components/Item-Card.vue
  web/src/components/Sub-Menu-UserFound.vue
  web/src/components/Sub-Menu-UserLost.vue
  web/src/router/index.js
  web/src/services/apiItems.js
  web/src/views/UserItems-Found.vue
  web/src/views/UserItems-Lost.vue
Labels: enhancement, task, back-end, front-end

#179 173/front/template do email de matches
  API/users/match.py
  API/users/migrations/0009_item_matches_alter_item_status.py
  API/users/models.py
  API/users/templates/emails/match_notification.html
  web/src/assets/icons/arrow-left.svg
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
  web/src/components/Item-Card.vue
  web/src/models/Form.js
  web/src/views/Found.vue
  web/src/views/ListItem.vue
  web/src/views/Lost.vue
Labels: bug, enhancement, task, back-end, front-end

#180 Feat(Testes): Criação e organização de folders e files para continuação
  API/AcheiUnB/tests/__init__.py
  API/AcheiUnB/tests/test_integration.py
  API/chat/tests/test_models.py
  API/users/tests/test_models.py
Labels: back-end

#181 Task(e-mail): Implementar notificações para o primeiro login
  API/AcheiUnB/settings.py
  API/AcheiUnB/static/dist/.vite/manifest.json
  API/AcheiUnB/static/dist/js/index-Ct_BI0hn.js
  API/celerybeat-schedule
  API/users/migrations/0009_userprofile_welcome_email_sent.py
  API/users/models.py
  API/users/signals.py
  API/users/tasks.py
  API/users/templates/emails/welcome.html
  API/users/views.py
  web/vite.config.js.timestamp-1738035132545-417108b6bc18f.mjs
Labels: enhancement, task, back-end

#185 feat(message): Criação da tela de mensagens, mudança do serializer da…
  API/users/tasks.py
  API/users/urls.py
  API/users/views.py
  web/src/router/index.js
  web/src/views/ListItem.vue
  web/src/views/Message.vue
Labels: task, back-end, front-end, javascript, python
