Repository unb-mds/2024-2-AcheiUnB, pull requests merged in 2025-06, with the labels that each got.

#270 Feat(Reports): adiciona sistema de denúncia e botão na página de item.
  API/AcheiUnB/settings.py
  API/AcheiUnB/settings_production.py
  API/AcheiUnB/urls.py
  API/docker-compose.prod.yml
  API/reports/__init__.py
  API/reports/admin.py
  API/reports/apps.py
  API/reports/migrations/__init__.py
  API/reports/models.py
  API/reports/serializers.py
  API/reports/tasks.py
  API/reports/tests.py
  API/reports/urls.py
  API/reports/views.py
  API/users/tasks.py
  web/src/views/ListItem.vue
Labels: enhancement, task, back-end, front-end, devops, javascript, python

#268 Fix(Item): ordenar itens por data de criação
  API/AcheiUnB/settings_production.py
  API/users/views.py
Labels: back-end, python

#274 Fix(logout): Efetiva o 'sair da conta' e permiti logins para servidores da unb não apenas alunos
  API/AcheiUnB/settings.py
  API/users/templates/emails/match_notification.html
  API/users/urls.py
  API/users/views.py
  web/src/components/Form-Found.vue
  web/src/components/Form-Lost.vue
  web/src/views/User.vue
Labels: bug, back-end, front-end, javascript, python

#281 feat(security): Implementacao de SAST e SCA na pipeline de CI #278
  .github/workflows/pipeline-ci.yaml
Labels: devops, python

#285 Update(Chat): Notificações, Chat e responsividade
  API/AcheiUnB/settings.py
  API/AcheiUnB/settings_production.py
  API/AcheiUnB/urls.py
  API/chat/models.py
  API/chat/serializers.py
  API/chat/tasks.py
  API/chat/templates/emails/chat_notification.html
  API/chat/views.py
  API/support/models.py
  API/support/serializers.py
  API/support/urls.py
  API/support/views.py
  API/users/signals.py
  API/users/tasks.py
  API/users/views.py
  API/websocket-server/index.js
  web/src/components/Header-Message.vue
  web/src/components/Main-Menu.vue
  web/src/components/Main-Menu.vue.css
  web/src/components/ReportProblemModal.vue
  web/src/views/Chats.vue
  web/src/views/Found.vue
  web/src/views/ListItem.vue
  web/src/views/Lost.vue
  web/src/views/Message.vue
  web/src/views/User.vue
  web/src/views/UserItems-Found.vue
  web/src/views/UserItems-Lost.vue
  web/src/views/UserProfile.vue
Labels: bug, task, back-end, front-end, devops, javascript, python

#290 Fix(Double Click): Corrigindo a criação de chats e envio de mensagem
  API/AcheiUnB/static/dist/index.html
  web/src/views/ListItem.vue
  web/src/views/Message.vue
  web/src/views/User.vue
Labels: bug, front-end
